/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/me3d.glb 
*/

import {useGLTF} from '@react-three/drei'
import {FC} from "react";

export const MeModel: FC = (props) => {
    const {nodes} = useGLTF('public/models/me3d.glb')
    return (
        <group {...props} dispose={null}>
            <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material}/>
        </group>
    )
}

useGLTF.preload('/me3d.glb')
